# Generated by Django 6.0.3 on 2026-03-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0006_add_candidate_created_at'),
        ('jd_app', '0006_jobdescription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Match score from 0.0 to 1.0')),
                ('match_type', models.CharField(choices=[('smart', 'Smart Match'), ('deep', 'Deep Search'), ('exact', 'Exact Match')], help_text='Type of matching algorithm used', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_candidates', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_candidates', to='jd_app.jobdescription')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['job', 'match_score'], name='ranking_job_job_id_a5ae99_idx'), models.Index(fields=['candidate', 'match_score'], name='ranking_job_candida_d5560a_idx'), models.Index(fields=['match_type'], name='ranking_job_match_t_8a5e79_idx')],
                'unique_together': {('job', 'candidate', 'match_type')},
            },
        ),
    ]
