# Generated by Django 6.0.3 on 2026-03-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_add_candidate_created_at'),
        ('jd_app', '0006_jobdescription_status'),
        ('ranking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='shortlisted', max_length=20)),
                ('match_score', models.FloatField(help_text='Match score from 0.0 to 1.0')),
                ('interview_stage', models.CharField(blank=True, choices=[('hr_round', 'HR Round'), ('technical_round', 'Technical Round'), ('manager_round', 'Manager Round'), ('final_round', 'Final Round')], max_length=20, null=True)),
                ('interview_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_funnels', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_entries', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_candidates', to='jd_app.jobdescription')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['job', 'stage'], name='ranking_rec_job_id_317b68_idx'), models.Index(fields=['candidate', 'stage'], name='ranking_rec_candida_18c208_idx'), models.Index(fields=['stage'], name='ranking_rec_stage_48f312_idx'), models.Index(fields=['created_by'], name='ranking_rec_created_283a42_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
