# Generated by Django 6.0.3 on 2026-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_add_created_by_to_jobcandidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcandidate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='recruitmentfunnel',
            name='match_type',
            field=models.CharField(blank=True, choices=[('smart', 'Smart Match'), ('deep', 'Deep Search'), ('exact', 'Exact Match')], help_text='Type of matching algorithm used (smart, deep, exact)', max_length=20, null=True),
        ),
    ]
