# Generated by Django 6.0.3 on 2026-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('hr_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_role', models.CharField(blank=True, help_text='AI-extracted job role/title', max_length=255, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='AI-extracted list of required skills', null=True)),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text='AI-extracted list of preferred skills', null=True)),
                ('min_experience', models.CharField(blank=True, help_text='AI-extracted minimum experience required', max_length=100, null=True)),
                ('experience_years', models.FloatField(blank=True, help_text='AI-extracted minimum experience in years', null=True)),
                ('salary_range', models.CharField(blank=True, help_text='AI-extracted salary range', max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='AI-extracted job location', max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, help_text='AI-extracted employment type (Full-time, Part-time, Contract, etc.)', max_length=100, null=True)),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='AI-extracted list of responsibilities', null=True)),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='AI-extracted list of qualifications', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='Timestamp when job description was analyzed by AI', null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of AI analysis', max_length=20)),
                ('analysis_error', models.TextField(blank=True, help_text='Error message if analysis failed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='jd_app_jobd_title_b6c8be_idx'), models.Index(fields=['analysis_status'], name='jd_app_jobd_analysi_53612f_idx'), models.Index(fields=['analyzed_at'], name='jd_app_jobd_analyze_b33b6b_idx')],
            },
        ),
    ]
