# Generated by Django 6.0.3 on 2026-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0004_add_analysis_status_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='matched_candidates',
            field=models.JSONField(blank=True, default=list, help_text='List of matched candidates with scores'),
        ),
    ]
