# Generated by Django 6.0.3 on 2026-03-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0005_jobdescription_matched_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Job status', max_length=20),
        ),
    ]
