# Generated by Django 6.0.3 on 2026-04-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0006_jobdescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsession',
            name='last_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
