# Generated by Django 6.0.3 on 2026-04-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0007_jobsession_last_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='job_session',
            field=models.ForeignKey(blank=True, help_text='Recruitment session this job belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_descriptions', to='jd_app.jobsession'),
        ),
    ]
