# Generated by Django 6.0.3 on 2026-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0008_jobdescription_job_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of skills'),
        ),
    ]
