# Generated by Django 6.0.3 on 2026-03-16 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True, help_text="Additional notes about the candidate's progress")),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='jd_app.jobdescription')),
            ],
            options={
                'verbose_name': 'Candidate Pipeline',
                'verbose_name_plural': 'Candidate Pipelines',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['candidate', 'job'], name='pipeline_ca_candida_96aa4f_idx'), models.Index(fields=['current_stage', 'updated_at'], name='pipeline_ca_current_017ff4_idx'), models.Index(fields=['job', 'current_stage'], name='pipeline_ca_job_id_c6cbef_idx')],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
