# Generated by Django 6.0.3 on 2026-03-16 19:41

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('education', models.JSONField(blank=True, default=list, null=True)),
                ('experience', models.JSONField(blank=True, default=list, null=True)),
                ('projects', models.JSONField(blank=True, default=list, null=True)),
                ('summary', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('upload', 'Manual Upload'), ('email', 'Email Ingestion'), ('api', 'API Integration')], db_index=True, default='upload', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chunked', models.BooleanField(db_index=True, default=False)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, db_index=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='candidates.resume')),
            ],
            options={
                'ordering': ['resume', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills_m2m',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='candidates.skill'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['uploaded_at'], name='candidates__uploade_9a0182_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['chunked'], name='candidates__chunked_f2da29_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['source'], name='candidates__source_069be5_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['candidate', 'uploaded_at'], name='candidates__candida_9c010e_idx'),
        ),
        migrations.AddIndex(
            model_name='resumechunk',
            index=models.Index(fields=['resume', 'chunk_index'], name='candidates__resume__5ffd64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumechunk',
            unique_together={('resume', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidates__email_188e48_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['phone'], name='candidates__phone_436030_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['name'], name='candidates__name_ed6dc8_idx'),
        ),
    ]
