# Generated by Django 6.0.3 on 2026-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
