# Generated by Django 6.0.3 on 2026-03-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_resume_uploaded_by'),
        ('jd_app', '0005_jobdescription_matched_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_session',
            field=models.ForeignKey(blank=True, help_text='Job session under which this resume was uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='jd_app.jobsession'),
        ),
    ]
