# Generated by Django 6.0.3 on 2026-03-21 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_onboarding_and_password_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_path', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'view_path')},
            },
        ),
    ]
