# Generated by Django 6.0.3 on 2026-04-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpagepreference'),
        ('jd_app', '0006_jobdescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_session',
            field=models.ForeignKey(blank=True, help_text='Default session to load automatically on login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='jd_app.jobsession'),
        ),
    ]
